#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
static double sum_avg;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */

void swap(int *p,int *q) {
   int t;
      
         t=*p; 
	    *p=*q; 
	       *q=t;
	       }

	       void sort(int a[],int n) { 
	          int i,j,temp;

		     for(i = 0;i < n-1;i++) {
		           for(j = 0;j < n-i-1;j++) {
			            if(a[j] > a[j+1])
				                swap(&a[j],&a[j+1]);
						      }
						         }
							 }


double * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  
  int n = input->input_data.input_data_len;

  double a[input->input_data.input_data_len];
  u_int k; 

  for(k = 0; k <= input->input_data.input_data_len; k++ )
  {
   a[k] = *dp;
   dp++;
  }
  
  sort(a, n);

  n = (n+1) / 2 - 1;
  sum_avg = a[n];
  
  if (n % 2 != 0)
  	sum_avg = (a[n] + a[n+1]) / 2;
  if (input->input_data.input_data_len == 2)
  	sum_avg = (a[0] + a[1]) / 2;

  /*  u_int i; */
   /* iterate until end of number of times (data_len) */
//  for( i = 1; i <= input->input_data.input_data_len; i++ )
//    {
//    sum_avg = sum_avg + *dp;  /* add what ptrs points  to ( '*' gets content ) */
//    dp++;
//    }

//  sum_avg = sum_avg / input->input_data.input_data_len;
  

  return( &sum_avg );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
